### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Sheeba-Samuel/REPRODUCE-ME#1]
Without a clear licensing statement, it is unclear what can be done with this ontology.

A good fit for ontologies is [CC0/Public Domain](https://creativecommons.org/publicdomain/zero/1.0/deed.en), with the understanding that attribution shall be provided through accepted norms of good scientific practice, rather than through copyright-based stipulations.

For some discussion around this topic, see [Create guidelines for OBO maintainers who want to be included in Wikidata](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/285).

**Comment by Sheeba-Samuel** [comment]
The REPRODUCE-ME ontology is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 2.0 Generic License. It was added to the ontology file. Now, I have mentioned the license in the README. Thanks for pointing out. @Daniel-Mietchen
